# Generated by Django 5.1.7 on 2025-03-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='mri_scans/')),
                ('file_format', models.CharField(max_length=10)),
                ('organ', models.CharField(blank=True, default='', max_length=50)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('slice_thickness', models.FloatField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MRIScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('file_name', models.CharField(max_length=255)),
                ('original_file_name', models.CharField(max_length=255)),
                ('organ', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
