# Generated by Django 5.1.7 on 2025-03-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MRI',
        ),
        migrations.AddField(
            model_name='mriscan',
            name='output_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mriscan',
            name='processing_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mriscan',
            name='segmentation_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
