# Generated by Django 5.1.7 on 2025-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0002_delete_mri_mriscan_output_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mriscan',
            options={},
        ),
        migrations.RemoveField(
            model_name='mriscan',
            name='output_data',
        ),
        migrations.RemoveField(
            model_name='mriscan',
            name='segmentation_data',
        ),
        migrations.AddField(
            model_name='mriscan',
            name='output_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mriscan',
            name='segmentation_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
