# Generated by Django 5.1.7 on 2025-03-14 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0003_alter_mriscan_options_remove_mriscan_output_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mriscan',
            name='scan_date',
            field=models.DateField(default=datetime.date(2025, 3, 14)),
        ),
    ]
