# Generated by Django 5.1.7 on 2025-03-15 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0004_mriscan_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mriscan',
            name='scan_date',
            field=models.DateField(default=datetime.date(2025, 3, 15)),
        ),
    ]
