# Generated by Django 5.1.7 on 2025-03-16 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0007_mriscan_prediction_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mriscan',
            name='scan_date',
            field=models.DateField(default=datetime.date(2025, 3, 16)),
        ),
    ]
