# Generated by Django 5.1.7 on 2025-03-16 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0008_alter_mriscan_scan_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mriscan',
            name='user',
            field=models.ForeignKey(default=213, on_delete=django.db.models.deletion.CASCADE, related_name='mri_scans', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
