# Generated by Django 5.1.7 on 2025-03-19 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0009_mriscan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mriscan',
            name='morphometry_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mriscan',
            name='morphometry_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mriscan',
            name='morphometry_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mriscan',
            name='scan_date',
            field=models.DateField(default=datetime.date(2025, 3, 19)),
        ),
    ]
