# Generated by Django 5.1.7 on 2025-03-22 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0010_mriscan_morphometry_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mriscan',
            name='morphometry_status',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='mriscan',
            name='scan_date',
            field=models.DateField(default=datetime.date(2025, 3, 22)),
        ),
    ]
