# Generated by Django 5.1.7 on 2025-06-29 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mori', '0012_alter_mriscan_scan_date_patienttimeline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineentry',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='timelineentry',
            name='mri_scan',
        ),
        migrations.AlterField(
            model_name='mriscan',
            name='scan_date',
            field=models.DateField(default=datetime.date(2025, 6, 29)),
        ),
        migrations.DeleteModel(
            name='PatientTimeline',
        ),
        migrations.DeleteModel(
            name='TimelineEntry',
        ),
    ]
